update caption to describe image
githubschool/flex pull request #23
Opened 2021-04-05 16:44 UTC by alexisrchapman

Here you can add: Additional requirements, steps to reproduce, etc.

PR Closes #2

2021-04-05 16:56 UTC, endersdestiny approved these changes
Looks good! Gotta love a kimono Cat!

2021-04-05 16:58 UTC, Kiranshettyj requested changes
Suggested changes

2021-04-05 16:58 UTC, Kiranshettyj commented on _slides/10-alexisrchapman.md
> +Welcome, from a cat in a Kimono!
```suggestion
Welcome, from a cat in a Kimono!, May be Hungry cat
```

2021-04-06 14:14 UTC, Kiranshettyj approved these changes

2021-04-06 14:27 UTC, merged